
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.froi.tresdirecciones.gramatica;

/** CUP generated class containing symbol constants. */
public class ParserPSym {
  /* terminals */
  public static final int SUMA = 2;
  public static final int MULTIPLICACION = 4;
  public static final int EOF = 0;
  public static final int NUMERO = 6;
  public static final int IGUAL = 8;
  public static final int error = 1;
  public static final int DIVISION = 5;
  public static final int PARC = 10;
  public static final int RESTA = 3;
  public static final int PARA = 9;
  public static final int ALFANUMERICO = 7;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SUMA",
  "RESTA",
  "MULTIPLICACION",
  "DIVISION",
  "NUMERO",
  "ALFANUMERICO",
  "IGUAL",
  "PARA",
  "PARC"
  };
}

